import type { Timeline } from "../types";

// Small built-in demo timeline so `remotion studio` works without running the
// pipeline first. Real renders pass --props=out/timeline.json.
export const sampleTimeline: Timeline = {
  fps: 30,
  width: 720,
  height: 1280,
  durationInFrames: 30 * 16,
  segments: [
    {
      id: "s0",
      narration: "If you live on GitHub, here is a repo you need to see",
      shot: "slide",
      slide: { kind: "terminal", props: { title: "trending", lines: ["$ git clone https://github.com/demo/repo", "Cloning into 'repo'...", "$ cd repo && ./install", "✓ 73k developers already on board"] } },
      captionStyle: "sans",
      start: 0,
      end: 3.4,
      words: [
        { text: "If you", start: 0.1, end: 0.6 },
        { text: "live on", start: 0.6, end: 1.1 },
        { text: "GitHub", start: 1.1, end: 1.7 },
        { text: "here is", start: 1.8, end: 2.3 },
        { text: "a repo", start: 2.3, end: 2.8 },
        { text: "you need", start: 2.8, end: 3.2 },
      ],
    },
    {
      id: "s1",
      narration: "The first is Ponytail",
      shot: "slide",
      slide: { kind: "kinetic", props: { text: "FIRST IS" } },
      captionStyle: "sans",
      start: 3.4,
      end: 5.4,
      words: [
        { text: "the first", start: 3.5, end: 4.2 },
        { text: "is", start: 4.2, end: 4.5 },
        { text: "Ponytail", start: 4.5, end: 5.2 },
      ],
    },
    {
      id: "s2",
      narration: "He says nothing. He writes one line. It works.",
      shot: "slide",
      slide: {
        kind: "repoCard",
        props: {
          name: "ponytail",
          fullName: "acme/ponytail",
          tagline: "He says nothing. He writes one line. It works.",
          stars: "73k",
          version: "v4.8.4",
          language: "TypeScript",
          license: "MIT",
          metrics: ["~54% less code (up to 94%)", "~20% cheaper", "~27% faster"],
        },
      },
      captionStyle: "serif",
      avatarBelow: true,
      start: 5.4,
      end: 9.0,
      words: [
        { text: "HE SAYS", start: 5.5, end: 6.1 },
        { text: "NOTHING", start: 6.1, end: 6.8 },
        { text: "ONE LINE", start: 6.9, end: 7.6 },
        { text: "IT WORKS", start: 7.7, end: 8.6 },
      ],
    },
    {
      id: "s3",
      narration: "It already has seventy three thousand stars",
      shot: "avatar",
      captionStyle: "sans",
      avatarCrop: "medium",
      start: 9.0,
      end: 11.6,
      words: [
        { text: "it already", start: 9.1, end: 9.7 },
        { text: "has", start: 9.7, end: 10.0 },
        { text: "73,000", start: 10.0, end: 10.8 },
        { text: "stars", start: 10.8, end: 11.4 },
      ],
    },
    {
      id: "s4",
      narration: "and it is growing fast",
      shot: "slide",
      slide: { kind: "starHistory", props: { fullName: "acme/ponytail", stars: 73000 } },
      captionStyle: "serif",
      avatarBelow: true,
      start: 11.6,
      end: 13.8,
      words: [
        { text: "AND IT IS", start: 11.7, end: 12.4 },
        { text: "GROWING", start: 12.4, end: 13.0 },
        { text: "FAST", start: 13.0, end: 13.6 },
      ],
    },
    {
      id: "s5",
      narration: "Comment repo for the link",
      shot: "slide",
      slide: { kind: "cta", props: { keyword: "REPO" } },
      captionStyle: "serif",
      start: 13.8,
      end: 15.8,
      words: [
        { text: "comment", start: 13.9, end: 14.6 },
        { text: "“REPO”", start: 14.6, end: 15.4 },
      ],
    },
  ],
};
